### ISSUE TITLE
Make zoom in frame?

### ISSUE THREAD

**Issue by fct-edilberto** [Microsoft/VoTT#119]
Is it possible to make zoom in frames modifying any config or archive?

**Comment by aribornstein** [comment]
Thanks for reaching out I will add this feature to the back log.

**Comment by cipri-tom** [comment]
Also to images, not just video frames ! Much needed feature

**Comment by aribornstein** [comment]
This is coming soon we had to do some rearchitecting to get this to work since the html5 video element doesn't support zoom. To get around this we turned the video element into a virtual control and added a canvas overlay in it's place which should enable zooming and filters in the near future.
