### ISSUE TITLE
 Can we only click on two points (the upper left corner and the bottom right corner), directly show this bbox?

### ISSUE THREAD

**Issue by whaozl** [Microsoft/VoTT#124]
I have a suggestion, at the beginning tagging bbox, Can we only click on two points (the upper left corner and the bottom right corner), directly show this bbox? This will be tagged much faster.

![1](https://user-images.githubusercontent.com/6327360/26973710-4ffa80c8-4d4a-11e7-9ac4-830b7021120b.png)

![2](https://user-images.githubusercontent.com/6327360/26973714-5439183e-4d4a-11e7-8720-8f68ea62cedf.png)

**Comment by whaozl** [comment]
**If I use the touch screen, this will be faster because I only need to click on two locations.**

**Comment by aribornstein** [comment]
This is now a feature in the dev version if you hold the ctrl keyyou can select two points instead of having to drag.
