### ISSUE TITLE
Enhancement request:  dynamic directory contents w/o losing tagging data correlation

### ISSUE THREAD

**Issue by rtrahms** [Microsoft/VoTT#134]
Hi -
The tool works great on JPG directories and AVIs, but when I use JPGs, I have discovered I have to be careful about keeping the contents of the directory unchanged during tagging sessions, otherwise I mess up the tagging information in the JSON file.  I found this out when I copied some additional JPGs into a directory after starting a tagging session.  The JSON file did not like this, and tags and images no longer correlated after a while.  I suspect the same is true for deleting images in a folder after a tagging session is started.

Of course the brute force way here is to delete the JSON file and start the tagging session over.  But if a user has tagged hundreds or even thousands of images, this is not work they would want to repeat.

Anyway, just an idea to improve an already excellent tool.  Thanks!
Rob

**Comment by aribornstein** [comment]
Hey this is a good feedback its caused by the way node reads in and indexes files by name. I will think of a way to address in the mean time i suggest writing a small script that adds a prefix to your new images to maintain order.

**Comment by rtrahms** [comment]
That is an okay workaround - I am using that currently to merge training sets.  I do have to manually merge train.txt and test.txt files though.

**Comment by cnrmck** [comment]
Was this issue ever addressed?
