### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ritazh** [Microsoft/VoTT#143]
- [x] Have hot keys for each tag
- [x] Make the pin to lock a tag more noticeable 
- [x] Make it possible to select the tags before making the rectangles in the image and keep those selected tags until manually changed
- [x] Have a color assigned to each tag to be able to see which tags are in each rectangle (colors should be on the border of the rectangles)
- [x] Have the ability to carry tags from one picture to the next using a command
- [x] Select multiple rectangles in the image and assign tags to the batch

**Comment by aribornstein** [comment]
- [ ] Add zoom in zoom out 
- [ ] Add filter support
- [ ] Add segmentation support

**Comment by ArkAung** [comment]
How do I "select the tags before making the rectangles in the image and keep those selected tags until manually changed"?
and
"Select multiple rectangles in the image and assign tags to the batch"

**Comment by abfleishman** [comment]
The ability to add hotkeys for a tag would make this tool 99% more efficient for my workflow.  Any chance that this could happen sometime soon?
