### ISSUE TITLE
CNTK-config.json file does not exist in /resource/app

### ISSUE THREAD

**Issue by concerttttt** [Microsoft/VoTT#147]
Perhaps because it is no longer needed? So please update the readme file.
Or should I manually create such a file?
Thanks.

**Comment by aribornstein** [comment]
Hey thanks for the feedback can you provide the context and steps which caused this error? I am unable to reproduce it.

**Comment by concerttttt** [comment]
The version I downloaded is VOTT-win32-x64.zip V1.0.8 for a 64-bit win10 desktop, after extracted the .zip file with the extract option in popup menu, I cannot find the .json file  in ./resource/app directory. 

After a bit of browsing, I found the file in ./resources/app/src/lib/detection_algorithms/cntkfastrcnn, not a big issue, just a little bit confusing.

Thanks though 👍

**Comment by aribornstein** [comment]
I must have migrated accidentally in the last release, will try to fix before the end of the week. Thanks for bringing this to my attention.
