### ISSUE TITLE
BUG: Tags not saving

### ISSUE THREAD

**Issue by abfleishman** [Microsoft/VoTT#148]
I am trying to tag images.  I used VoTT (downloaded on 10 Nov 17) on a Windows machine to tag a few 100 and then closed the program.  I then moved to a different computer (Mac) and continued tagging ~800 more photos.  I saved, (cmd+s) and got a message that it successfully saved and I closed VoTT.  When I opened the program latter none of my new tags were there.  Also, the json file's modified time reflected the first tagging session, not the second.  I have now done some testing and when I change pages or save, the json file does not update.  I am tagging on an external harddrive (USB). Any thoughts?

**Comment by abfleishman** [comment]
I just tried to tag a new image directory and when I save it says  it successfully saved but no json file is created.

**Comment by aribornstein** [comment]
Thanks for letting me know. Most of the tagging i've done has been on the same OS. I will test cross platform tagging and let you know if i can reproduce and resolve.

**Comment by abfleishman** [comment]
I think I have tracked it down to the formatting of the HD i was using so the only bug is that it says it is saving successfully and it was not.
