### ISSUE TITLE
No new lines in all files for the yolo exporter

### ISSUE THREAD

**Issue by soldumais** [Microsoft/VoTT#149]
https://github.com/Microsoft/VoTT/blob/8fcf1bc1db4447187c89da86f4f47f4747119ad1/src/lib/detection_algorithms/yolo/exporter.js#L10

I've changed all \n for \r\n in yolo/exporter.js and the Yolo exporter seem to be work now

**Comment by aribornstein** [comment]
Thanks for bringing this to my attention I will validate this patch and update the code later this week
