### ISSUE TITLE
The image disp window is blank.

### ISSUE THREAD

**Issue by back2yes** [Microsoft/VoTT#150]
The app does not show any images in its window, the images in the specific folder is in .jpg format. Should I install some other libraries such as opencv? The annotating functions work fine.
The platform version is windows 7.

**Comment by aribornstein** [comment]
That is strange. You shouldn't need any other libraries since vott uses the html5 video canvas poster feature to load images. Can you running VoTT directly from git with node and see if that resolves your problem?
