### ISSUE TITLE
Format Converter on annotations

### ISSUE THREAD

**Issue by kyoro1** [Microsoft/VoTT#151]
As we find in README.md in the top folder, we have some formats:

```
Exporting tags and assets to CNTK , Tensorflow (PascalVOC) or YOLO format for training an object detection model.
```

Then, if we have already completed adding annotations for Faster R-CNN(CNTK), can we have a kind of format-convert to Yolo? (Or other directions like Yolo to CNTK...) Perhaps, is it required to generate by ourselves?

**Comment by aribornstein** [comment]
Did you generate your cntk annotations with Vott? If so should be able to just reload the Annotations into Vott and just export them as yolo.

**Comment by nolancardozo13** [comment]
Any update on this? I have CNTK annotations generated by VOTT and would like to use these to convert to YOLO or Pascal VOC. I do not think VOTT has this functionality at present.

**Comment by aribornstein** [comment]
Yes this is something i have added to the backlog what i recommend is that you share the .json file generated by vott in the same directory as your image and video assets that should save you from having to reproduce all the tags.
