### ISSUE TITLE
Integration of VOTT to a web application

### ISSUE THREAD

**Issue by ajaysharmahcl** [Microsoft/VoTT#152]
Hello ,

I want to integrate VOTT tool into a .net based web application so that user can tag a new image and submit back to system. I tried adding the div from index.html into an aspx page and call required js files but it does not work that way. Please suggest required steps to inject VOTT image frame along with tagging options.

Thanks in advance,
Ajay

**Comment by ajaysharmahcl** [comment]
Dear All ,

i have integrated VOTT code files into web application and tried to run. installed few things and modified the script files too as required. I am stuck to index.js file now. It throw error when i try to run it as below -

Uncaught Error: Module name "electron" has not been loaded yet for context: _. Use require([])
http://requirejs.org/docs/errors.html#notloaded

i have installed nodejs and require.js separately too but no  luck. Could anyone please help to know why require(..) method is not defined and does not recognized any module? quick help would be highly appreciated. 

Happy new year to all GIT friends..

Many Thanks
Ajay

**Comment by aribornstein** [comment]
The issue you are getting is that some of the client and server logic are mixed together. If you want the app to work on the web you're going to have to find some alternatives for the electronic components which are OS specific. 

Happy to help point you in the right direction can give me a little bit more context of what you're trying to do with the web application? I'd love to support.

**Comment by ajaysharmahcl** [comment]
Thanks a lot Ari for responding. Here is what i am trying to achieve -

- I have a asp.net based web application that is used for image detection through faster rcnn model 
- Integrate VOTT in web application for tagging new image. I want to use VOTT tool within same web application (VOTT UI frame on aspx page)  for tagging new image so that user do not need to go away from the web application page for tagging new image

i have extracted source code of VOTT from GIT and added to solution. I am stuck on require method which is not able to find electron module. I have searched this module in VOTT package and node package both but could not locate it. Could you please suggest where this module exist?

Thank you in advance for help.

**Comment by aribornstein** [comment]
As mentioned before the electron is a platform that bundles node and chromium to make cross platform apps. It can't be embedded in a website https://electronjs.org. To achieve what you want you have two options you have to:

- Do a little bit of work to decouple the electron logic and node logic from the client side logic in VoTT
- Or you can just reuse the [videotagging control](https://github.com/CatalystCode/video-tagging) we wrote and take the export and tracking scripts and apply them as needed into your solution 

I am currently working on a solution for this you might want to look at some of our [previous work](https://github.com/CatalystCode/VideoTaggingTool) here

**Comment by ajaysharmahcl** [comment]
Thanks a lot ari for providing alternatives. It is greatly helpful but i am seeing some integration issue- 

i setup videotagging control and successfully ran demo of it too using local server. When i integrated this with visual studio solution it started giving error for type scripts. Build failed with module not found (all module defined in .ts files). 
Examples of error is as below -

Severity	Code	Description	Project	File	Line	Suppression State
Error	TS2307	Cannot find module 'url'.	TypeScript Virtual Projects	C:\video-tagging\bower_components\hydrolysis\src\analyzer.ts	14	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error		Build:File 'C:/video-tagging/bower_components/hydrolysis/typings/main.d.ts' not found.		


Any pointer why type script error coming when building the project solution Please?

**Comment by aribornstein** [comment]
Yes it it seems like there is a missing bower dependency.

**Comment by aribornstein** [comment]
These dependencies on bower will be removed in the latest release making it easier to reuse the annotation control contained in VoTT for your own video/image tagging work flow

**Comment by leopoldjoy** [comment]
> I am currently working on a solution for this you might want to look at some of our [previous work](https://github.com/CatalystCode/VideoTaggingTool) here

@aribornstein Any progress on this? Is this any implementation of VoTT setup for web now?
