### ISSUE TITLE
Box size and position change after reloading image. Windows 7

### ISSUE THREAD

**Issue by BigBorg** [Microsoft/VoTT#156]
After I click next image and then click previous image, the boxes I drew changed! They become smaller and moved up a little!

**Comment by BigBorg** [comment]
I have to move to next image and go back to correct the boxes. After this, they stay fixed. But I have to draw boxes twice for each image.

**Comment by aribornstein** [comment]
This behavior shouldn't happen. Can you provide reproduction steps?

**Comment by maldivien** [comment]
Im having the same issue with wnodws 10, if i add more images to the annotation folder then previous annotations mess up. I can only fix those after i delete the files that i added later. very strange. still trying to figure out the issue. i suspect something with file names..

**Comment by smd-faizan** [comment]
Same behavior on my Windows 10 system.

**Comment by aribornstein** [comment]
This should be fixed in the upcomming release.
