### ISSUE TITLE
File names with open/close brackets dont work

### ISSUE THREAD

**Issue by maldivien** [Microsoft/VoTT#160]
I have to remove the brackets after renaming files because VoTT cant read them.

**Comment by aribornstein** [comment]
That's an interesting bug I will take a look at it over the Upcoming week and resolve

**Comment by maldivien** [comment]
I found something else too, if i add more image files to the annotated directory the when i open the project again the boxes mess up, and to fix it i have to rename with an alphabet that comes after the last annotated filenames first character..very strange but  have proven this through tests. 

for example: if have images in a folder that starts with box1, box2, box3 ... then if i add anything that starts with A then t mess up, it has to be a char after character 'B'.

**Comment by wbreza** [comment]
We are not able to reproduce this issue.  Please let us know if you continue to have issues.
