### ISSUE TITLE
menu Debug->Refresh App

### ISSUE THREAD

**Issue by donaldlee2008** [Microsoft/VoTT#161]
Debug->Refresh App is  bad designed here .
 I worked 3 hours to tag the pictures. and  some object is very near by the menu Debug.
I was wrong to click to the Debug->Refresh App. then everything was over.
in the past 3 hours. I was at least wrong click to Debug  and one time click to Refresh App. because it is so closed to the object.
 I think the Refresh App should have a pop up dialog ta ask if given up the previous work....
--------------------------------------------------
thanks god, I open it again, all thing are still there!

the menu is so close to the work space. hope can improve in next version

**Comment by aribornstein** [comment]
I will take a look glad you were able to recover your tags.
