### ISSUE TITLE
VOTT hangs while exporting 5000+ records to tensorflow pascal voc

### ISSUE THREAD

**Issue by maldivien** [Microsoft/VoTT#162]
It hangs but it seems to have created all files But only creates partial entries in text files at ImageSet/Main/.

**Comment by aribornstein** [comment]
Thanks for the feedback this is a known issue and a fix is in the backlog.

**Comment by jpedrofontes** [comment]
Any developments in this? I have a dataset with 10000+ images and the app presents a black screen where the images for tagging should be, not allowing me to tag a single image.

**Comment by aribornstein** [comment]
Resolving this will take some restructuring since exporting writes to disk one file at a time it can be a slow process now i would recommend writing a script to process the .json file associated with the app.
