### ISSUE TITLE
display category using color or when moving mouse over BBox would be helpful

### ISSUE THREAD

**Issue by vieuxcheval** [Microsoft/VoTT#165]
currently all Bboxes are in blue. when reviewing there is no way to see their categories. it would be helpful to display category  when moving mouse over BBox. an even better way is to display category text box and BBox using same color, which is assigned in some order or randomly.

**Comment by aribornstein** [comment]
This is has been fixed in the latest version of the code. You can check it out by cloning the repo and using

npm install
npm start
