### ISSUE TITLE
VOTT and multi-labelling

### ISSUE THREAD

**Issue by DaireNiC** [Microsoft/VoTT#166]
Is it possible to assign multiple labels to one bounding box for multi-label classification?

**Comment by aribornstein** [comment]
It's a good idea I will add this to the back log and put it in the next release with a ctrl-click shortcut.

**Comment by aribornstein** [comment]
This has been included in the latest dev build

**Comment by pierrelzw** [comment]
Hi @aribornstein thanks for your work, how can I activate multi-labeling for one box?
