### ISSUE TITLE
Doesnt export tag tsvs for all labeles images

### ISSUE THREAD

**Issue by ampatha** [Microsoft/VoTT#168]
I tested both in linux and and windows. Complete tagging ie 6 images, only exports the tsvs of 2 of them in the positive 1 of them in the test folder. If I try to export 1 by 1 it removes previous tags and  saves only the last exported ones. IE done tagging 20 images, managed to get only the tsv of 1 image out of 20.

**Comment by aribornstein** [comment]
Are you using the latest build from master? I recommend cloning the repo and trying the two following commands
npm install
npm start

Should fix this issue.
