### ISSUE TITLE
Clarification: full installation method (non pip) of CNTK)

### ISSUE THREAD

**Issue by DaveVoyles** [Microsoft/VoTT#187]
[The README states:](https://github.com/Microsoft/VoTT/blob/master/README.md)

> Install CNTK (Note: currently the tool only supports the full installation method (non pip) of CNTK).

Does this mean only the [Windows Binary Manual installation](https://docs.microsoft.com/en-us/cognitive-toolkit/setup-windows-binary-manual) process?

**Comment by aribornstein** [comment]
It means to use the script installation in c:\local
