### ISSUE TITLE
ImportError: No module named 'cntk_helpers' when running C1_DrawBboxesOnImages.py

### ISSUE THREAD

**Issue by DaveVoyles** [Microsoft/VoTT#188]
**OS:** Ubuntu Deep Learning VM

**Steps to reproduce:** 

1. Label images with VoTT
2. Export in CNTK Fast-RCNN format
3. Clone CNTK from GitHub
4. Drop images into Datasets/MyFolder 
5. In C1_DrawBboxesOnImages.py, change imgDir to directory where images are located
             EX: "imgDir = _"/home/dave/notebooks/CNTK/Examples/Image/DataSets/Helmets/positive"_
6. Run this command: ```python C1_DrawBboxesOnImages.py```

Error returned:

```
dave@dv-dlvm-linux:~/notebooks/CNTK/Examples/Image$ python /home/dave/notebooks/CNTK/Examples/Image/Detection/utils/annotations/C1_DrawBboxesOnImages.py
Traceback (most recent call last):
  File "/home/dave/notebooks/CNTK/Examples/Image/Detection/utils/annotations/C1_DrawBboxesOnImages.py", line 10, in <module>
    from cntk_helpers import *
ImportError: No module named 'cntk_helpers'
```

![image](https://user-images.githubusercontent.com/1786053/40323049-3b799cc4-5d02-11e8-9729-58224d62f77e.png)

I've verified that cntk_helpers exists:
*/home/dave/notebooks/CNTK/Examples/Image/Detection/FastRCNN/BrainScript/cntk_helpers.py*

**Comment by aribornstein** [comment]
VoTT prevents you from needing to run this script the data should already be exported with tags and the labels you need.
