### ISSUE TITLE
Feature request: When tagging images, show the image name at the top of the screen

### ISSUE THREAD

**Issue by tobsecret** [Microsoft/VoTT#189]
I have images that take a trained eye to annotate but luckily I have a description text file for each image. Tagging the images would be much easier if I knew their filename. Hope this would not be too much of an issue.

**Comment by aribornstein** [comment]
This should already be supported are you using the latest version of the code?

![image](https://user-images.githubusercontent.com/3045407/40409913-f485cfb2-5e74-11e8-9ebe-e8200ba86a79.png)

**Comment by tobsecret** [comment]
It is working now - looks like it just did not show it for the first couple
of images.
