### ISSUE TITLE
VoTT appends extra dot "." into the filename for images in .jpeg file

### ISSUE THREAD

**Issue by ljchiu** [Microsoft/VoTT#191]
work around is to rename all images in your dataset to .jpg.  Or hack reate_pascal_tf_record.py code and remove the extra dot in the section where it is reading the .xml annotation file. Do that by changing:

full_path = os.path.join(dataset_directory, image_subdirectory, data['filename']+'.jpg')

to

full_path = os.path.join(dataset_directory, image_subdirectory, data['filename']+'jpeg')

**Comment by aribornstein** [comment]
Please submit a pull request.
