### ISSUE TITLE
Tagging issues with files less than 200 pixel height. While tagging such images, the moment you release the mouse after drawing the rectangle and clicking the tag value the drawn rectangle suddenly becomes small.

### ISSUE THREAD

**Issue by brijrajsingh** [Microsoft/VoTT#192]
**Steps to Reproduce**

- Pick a less than 200 pixel height image
- Draw the rectangle, release the mouse
- Click on the tag to select
- Suddenly the rectangle will shift upwards and become very small in height​

**Workaround**
- Pick a less than 200 pixel height image
- Draw the rectangle, release the mouse
- Resize the rectangle, any resizing motion will do, even if it comes back to the same size.
- Click on the tag to select, Now the rectangle won't resize

**Comment by aribornstein** [comment]
Thanks for bringing this to our attention I will work to reproduce and let you know what I find.
