### ISSUE TITLE
Bounding box jumps to another location

### ISSUE THREAD

**Issue by Keessie** [Microsoft/VoTT#193]
After dragging a bounding box, when clicking one of the label tags, the bounding box shifts up in the screen. Which annoyingly requires the user to move the bounding box back to the desired location after choosing a label.

When the bounding box is created first, has been relocated, and then tagged, there is no jumping/shifting of location happening.

**Comment by aribornstein** [comment]
Hmm this should have been fixed are you using the latest version of VoTT? If so can you provide reproduction steps?

**Comment by Keessie** [comment]
Hi aribornstein, 

Re-installing fixed most of the problems, thanks!
