### ISSUE TITLE
Copy Last region selected method seems not to work on 1.5.0

### ISSUE THREAD

**Issue by aznedy** [Microsoft/VoTT#201]
Hello,

It seems that the when the suggested region method is set on 'Copy Last' in the video tagging configuration, that it does not work as it has in previous versions of the tool. The box either doesn't appear, or it appears in a different spot. 

This increases the time I am spending tagging by at least twice. 

It is also of note that if the tracking option is selected, that the boxes seem to move in a somewhat erratic fashion. 

Both options are unusable for me in the new version. Which is keeping me on the older version 1.0.0. 

Perhaps this is a problem with my setup, but I have tested between versions pretty extensively, and I cannot find a way to make this work. Any insight would be gladly appreciated. 

Thanks

**Comment by aribornstein** [comment]
Thank for letting us know I will look into this and follow up!

**Comment by aznedy** [comment]
If there is any more info that I can provide, I'm more than happy to.

**Comment by kodonnell** [comment]
Can second this - when we tried a month ago it was working on Mac but not on Windows (the copy last progressively moved further right). Unfortunately, as far as we could tell, it also corrupted the entire video tagging when we turned it on part-way through and we had to start again.

We're looking at using VoTT again so I might look into this if it's still a problem.

**Comment by kodonnell** [comment]
OK, this appears to be related to window size - we discovered opening the debug console changed the behaviour, which pointed to window width. If you resize the window so there's no grey padding around the image, it works as expected. Investigating further now, though might be quicker for someone else who knows the internals.

**Comment by kodonnell** [comment]
OK, things look messier than first expected. If there's padding on the left/right, then I can hack a fix by subtracting this [here](https://github.com/Microsoft/VoTT/blob/df1160be825bd1ce62c13e2360471185308ddb7b/src/lib/tracking_algorithms/videotagging-tracking-extension.js#L119). However, doing the same for padding on top doesn't work so well. In addition, if there's padding on top, you can't even draw boxes in the right place - they jump upward. This seems like a similar problem (not accounting for the padding in calculations), so maybe the problem goes deeper. There might be a more sensible way to fix this, so I'll leave to @aribornstein 

FYI by 'padding on top' I mean:

![image](https://user-images.githubusercontent.com/8204904/42140441-a0d0ff24-7df3-11e8-9272-24bd341f1063.png)

Working on latest in master.

**Comment by aribornstein** [comment]
Can you try to see if you can reproduce this from the dev branch?

**Comment by kodonnell** [comment]
On dev branch:

- The boxes appear to same in the same place when I draw them with 'padding on top' (unlike master)
- Tracking doesn't seem to work at all - when I move to the next frame, the boxes all disappear. I'm not sure if this is because they're disappearing properly, or being shifted offscreen.

**Comment by aribornstein** [comment]
Glad the issue with duplicate was resolved. Unsupervised tracking is an imperfect feature due to the camshift.js algorithm it may not work for every object or every video. This is why VoTT provides both the duplicate and the ability to toggle tracking.

Hope this helps at a later point we will revisit the available tracking algorithms in js to upgrade this feature,

**Comment by kodonnell** [comment]
@aribornstein - by 'tracking' I simply mean 'Copy last region' i.e. copy the boxes from the last frame to this one. I will update the comment to reflect that. To be clear, 'copy last region' still does *not* work, and I'd consider this a pretty large bug (and also pretty easy to fix). Could you please re-open, or remove the feature from the tool and documentation until it's fixed? Broken functionality is bad in many ways, but especially when it can corrupt an existing annotation if turned on part-way through.

**Comment by kodonnell** [comment]
@aribornstein could you please reopen? I think I've seen two other issues mentioning this.

**Comment by kodonnell** [comment]
Update:

> On dev branch:
> The boxes appear to same in the same place when I draw them with 'padding on top' (unlike master) 'Copy last region' doesn't seem to work at all - when I move to the next frame, the boxes all disappear. I'm not sure if this is because they're disappearing properly, or being shifted offscreen.

It appears this is a separate issue - the boxes *are* in the right place, but they're just not visible. I only discovered by opening the debug console, which makes the boxes appear (presumably due to a resize trigger or some such). @aribornstein - this sounds like an easy fix, but I'll close this issue as it seems to be resolved on dev. Could you please give an ETA on when a new release will be pushed with the current dev branch?

**Comment by gurkirt** [comment]
@kodonnell I am facing the same issue. 'Copy from the last frame' does not appear to copy boxes from the previous frame to current frame. How did you solve it?

**Comment by kodonnell** [comment]
@gurkirt - I solved it by not using VoTT. Last I tried, the dev branch 'worked' as above - just with invisible boxes. @aribornstein can possibly implement a quick fix for this, as it seems pretty minor.

**Comment by gurkirt** [comment]
@kodonnell what did you use? I tried dev branch but no luck. Like you said box in next frames goes invisible. I haven't worked with JS before, any idea where the fix is going to be very helpful.

**Comment by kodonnell** [comment]
I think it turned out we didn't need anything extra, and just stuck with the data we already had, unfortunately. You could try hitting CTRL D (i.e. open the debug console - and maybe hit it again to close it) which did show the boxes if I remember correctly.

**Comment by gurkirt** [comment]
Hey @kodonnell, thanks, ctrl+D does work. Really appreciate your prompt replies. 

@aribornstein  where do you think is the issue, I haven't used JS before but I kinda got the flow of VOTT. May if you can suggest where exactly could be is the issue then I can try to fix it. 

Also, the current dev version solves my problem on another issue https://github.com/Microsoft/VoTT/issues/21.

Cheers
Gurkirt

**Comment by kodonnell** [comment]
OK, I've just had a snoop around the dev branch - it looks like @aribornstein has changed the way regions are handled on the dev branch, but hasn't got round to updating the tracking algorithms to use this new approach. So - 'copy last frame' won't work at all. It probably isn't too hard to change for someone who knows what they're doing. For someone new to it ... I suggest start by changing `$('.regionCanvas')` to `self.videotagging.regionManager.regions` in `videotagging-tracking-extension.js` and going from there.

@aribornstein - as above, can we please reopen this issue when you're back from holiday?
