### ISSUE TITLE
Unable to load videos in formats other than ".mp4" format

### ISSUE THREAD

**Issue by anubhayal** [Microsoft/VoTT#208]
I was trying to tag a video which was in ".mpg" format but i think VoTT doesn't support any format other than ".mp4". So, I have made some changes in index.js script but even after that the changes are reflected in application UI only. I didn't find anything other than this where I could make relevant changes.

Suggest me some steps to make required changes in the scripts or is there anything to do with libraries included. 

PFA screenshot for more details.
![mp4](https://user-images.githubusercontent.com/19743400/42691462-cb6f77bc-86c5-11e8-9918-e96e84eac16c.png)
![mpg](https://user-images.githubusercontent.com/19743400/42691470-cf5d53ee-86c5-11e8-88cc-b13822014aef.png)

**Comment by aribornstein** [comment]
VoTT supports only the video formats that are supported by the html5 video https://www.w3schools.com/htmL/html5_video.asp control other videos will need to be converted using a tool such as ffmpeg.

**Comment by anubhayal** [comment]
Thanks :) @aribornstein
