### ISSUE TITLE
Exported images from video are incorrectly cropped

### ISSUE THREAD

**Issue by kodonnell** [Microsoft/VoTT#210]
When exporting from a video, them images were cropped from what they were in the video. The bounding boxes were correct with regards to the full frame, but not correct with regards to the cropped frame, and hence the results were useless.

I strongly suspect this is to do with padding (as discussed in #201, where it's causing a lot of other issues).

**Comment by aribornstein** [comment]
This was an issue with the dev build should be resolved in the latest release
