### ISSUE TITLE
Unable to run - npm start error

### ISSUE THREAD

**Issue by nileshlg2003** [Microsoft/VoTT#213]
Hi All,

I'm trying to run it on Mac, I have cloned the project, did ``` npm install ``` and when I try to run the application using ``` npm start ```, it gives be following error,

```
[1428:0716/210359.721964:FATAL:v8_initializer.cc(249)] Couldn't mmap v8 natives data file, status code is 1

```
Is anyone else experiencing this?  How to solve it?

**Comment by aribornstein** [comment]
Hmm that's strange I have been unable to reproduce can you try delete the cloned directory reclone from dev and trying again.

**Comment by nileshlg2003** [comment]
I deleted the clone and re cloned it, I can confirm its working now. Thanks
