### ISSUE TITLE
Annotation of Polygons / Contours

### ISSUE THREAD

**Issue by Legor** [Microsoft/VoTT#221]
I think it would be a nice addition to allow annotation of object contours e.g. by polygons.
Is anyone allready working on this?

Best wishes.

**Comment by ahirner** [comment]
Hi @Legor, for what input data (video/images/domain) you will use it for? For the most basic needs, the via tool could help (http://www.robots.ox.ac.uk/~vgg/software/via/).

**Comment by Legor** [comment]
Hey @ahirner, thanks for the suggestion. Haven't checked this one out yet. I'll use it mainly for video footage/video frames.

**Comment by aribornstein** [comment]
This is currently in the backlog hopefully we'll have it in a future release. Would be happy to have contributors on this feature!

**Comment by kichinsky** [comment]
Point-based polyline/polygon support is now under development.

**Comment by kichinsky** [comment]
Added polyline support in #374. Polygons are comming soon.
