### ISSUE TITLE
Annotation output greater than image dimensions

### ISSUE THREAD

**Issue by omair-kg** [Microsoft/VoTT#223]
I have an image with the resolution 1280x720. When I label an object at the bottom right corner of the image,'x2' and 'y2' in the json file are 1500 and 727 respectively. Do you know what is going wrong here? I'm using the latest release package.

**Comment by aribornstein** [comment]
I believe the cordinates are relative coordinates not absolute cordinates. What format are you exporting to?

**Comment by omair-kg** [comment]
I am importing the output of a detector as a compatible json file and then reading that into VoTT to ease manual labeling. In VoTT it doesn't work properly though because of the relative coordinate system. Is there any way to work around this?

**Comment by aribornstein** [comment]
I would recommend converting the absolute coordinates to relative coordinates using the hight and width of your image. VoTT uses relative coordinates for both backwards compatibility and scaling purposes.
