### ISSUE TITLE
add new label class on the fly

### ISSUE THREAD

**Issue by abfleishman** [Microsoft/VoTT#226]
It would be really nice to be able to add a new class once a session has already started

**Comment by aribornstein** [comment]
I'm pretty sure it will work if you refresh the session and add a new tag in the load screen can you confirm?

**Comment by abfleishman** [comment]
Yes, it works, but it loses my place (the photo I left off on) and it would be really nice to be able to just right click/keyboard shortcut in the label area and type a new label since it is a bit disruptive to refresh the session.  

I guess this would be a lower priority enhancement though since as you pointed out it does allow the addition of labels.
