### ISSUE TITLE
Enhancement request: Zoom in/out

### ISSUE THREAD

**Issue by yangulei** [Microsoft/VoTT#227]
Thanks for sharing this useful tool.
So far, it's difficult to label relative small objects in high resolution images, like the ones taken by UAVs.
Please consider this to make it better, great thanks!

**Comment by aribornstein** [comment]
Thanks for the feedback this is in the backlog glad you are enjoying the tool

**Comment by jcpayne** [comment]
As of Apr 24, 2019 it is still not possible to zoom in to parts of the full-size image.  Vott is useless for high resolution images without that ability.  Please consider adding it.

**Comment by SB2020-eye** [comment]
> Thanks for the feedback this is in the backlog glad you are enjoying the tool

Is there a status update on this? Thanks.
