### ISSUE TITLE
Labels are positioned in the wrong location after Active Learning using FasterRcnn 

### ISSUE THREAD

**Issue by i02fesea** [microsoft/VoTT#228]
Hi everyone,

I am training a model defining the dimension size 300x300 and using pictures size 224x171. I load the pictures and run the active learning option. The active learning works fine, but the labels are positioned in the wrong location. The x axis is fine, but the y axis is offset to a wrong location. I think that there is a problem calculating the borders.

I would appreciate any help!

![errorlocationlabels](https://user-images.githubusercontent.com/12471064/45301445-44e91e80-b511-11e8-8f40-bf51ae32cd5a.jpg)

**Comment by aribornstein** [comment]
Are you using the latest release this should be resolved try the dev branch

**Comment by JacopoMangiavacchi** [comment]
Yes this issues is related to previous version (v1) of VoTT.  Could you please try again with v2 and eventually re-submit an issue with updated info.  Thanks
