### ISSUE TITLE
BUG: extending existing bounding box

### ISSUE THREAD

**Issue by abfleishman** [Microsoft/VoTT#249]
When I extend a bounding box that has already been made by dragging the left side I can extend the box off the image.  on the top, bottom or right side of the bounding box does not pass the edge of the image.

**Comment by kichinsky** [comment]
Is it the master or dev branch? We rebuild the tagging engine for the new version of VoTT.

**Comment by kichinsky** [comment]
Yeah, it should be fixed in dev.
