### ISSUE TITLE
move/reorganize/re-color tag buttons 

### ISSUE THREAD

**Issue by GondekNP** [Microsoft/VoTT#252]
This is covering a few things regarding the label tray that is currently on the bottom on the VoTT screen - 
-if the color for a label/bounding box is light, the label becomes very difficult to read when selected. For example;
![image](https://user-images.githubusercontent.com/20877429/46111936-a0680d00-c19d-11e8-87a5-a8f5e182497c.png)

-it would be useful to be able to reorder the tags in the label tray, either by dragging and dropping, sorting alphabetically, or sorting by the frequency of the tag being used on the dataset. We are usually using the same 5-10 tags over and over again, and while we do occasionally use the extras, it would be nice to organize them in a more logical way so that our most used ones are all together. 

-lastly, it would be great to be able to move the entire tray to a different portion of the VoTT window. Our images are in a 4:3 aspect ratio, and if we could move the label tray to left or right side, we could make our images bigger and our tagging more precise.

**Comment by wbreza** [comment]
Tag panel has been fully re-designed in v2.0.0
