### ISSUE TITLE
Output JSON should contain file names

### ISSUE THREAD

**Issue by bnookala** [Microsoft/VoTT#260]
If we load a directory of images into VoTT, proceed with tagging, and save, the output JSON is a dictionary with zero-indexed keys (stored as strings), that maps to a list of tags per frame.

We're currently building tooling around VoTT, and expect to preserve file names somewhere within the output JSON, hoping to avoid keeping a map of frame indexes to file names on the tagger's machine.

**Comment by mtarng** [comment]
Current json output for frames:

```
"frames": {

        "0": [...],

        "1": [...],

        "2": [...],

        "3": [...],

        "4": [...]
    }
```

desired output:
```
"frames": {

        "st1020.png": [...],

        "st1021.png": [...],

        "st1022.png": [...],

        "st1023.png": [...],

        "st1024.png": [...]

    }
```

**Comment by PIC123** [comment]
This has been addressed in the dev branch, working on creating a release for master

**Comment by mtarng** [comment]
@PIC123 any updates on when the release will occur?

Also, if I've found a bug on the current 'dev' branch, should I open an issue here? Basically the 'visitedFrames' has inconsistent naming, the first element is the filename only, subsequent entries have the full filepath.

```    
"visitedFrames": [
        "1012.png",
        "/Users/mtarng/Downloads/small-image-set/1210.png",
        "/Users/mtarng/Downloads/small-image-set/1238.png",
        "/Users/mtarng/Downloads/small-image-set/1576.png",
        "/Users/mtarng/Downloads/small-image-set/1748.png",
        "/Users/mtarng/Downloads/small-image-set/1760.png",
        "/Users/mtarng/Downloads/small-image-set/1774.png"
    ]
```

**Comment by bnookala** [comment]
@PIC123 I took a look at the source, and found where the iissue that @mtarng is describing above;

Presently in the dev branch, l


However, line 463 in the same file has this: 

```
visitedFrames = new Set([videotagging.imagelist[0]])
```


```
videotagging.imagelist = videotagging.imagelist.map((filepath) => {return path.join(pathName,filepath)});
```

A

**Comment by PIC123** [comment]
@bnookala @mtarng Sorry for the late reply, I just realized that this is actually an issue with windows vs unix. Will push a fix soon
