### ISSUE TITLE
Error running VoTT Release V1.5.0 on Ubuntu 18.04.1 LTS

### ISSUE THREAD

**Issue by Smarker** [Microsoft/VoTT#267]
I am on `Ubuntu 18.04.1 LTS`. I downloaded the `V1.5.0` release for Linux, extracted the files, and tried to run the VoTT executable.

When I ran the executable I got:
```
./VoTT: error while loading shared libraries: libgconf-2.so.4: 
cannot open shared object file: No such file or directory
```

To fix this problem I ran:
```
sudo apt-get install -y libgconf-2-4
```

As this is an electron app, I suggest looking at this issue: https://github.com/electron/electron/issues/1518

After this, I was able to launch the VoTT executable, but I still got `Gtk-Message: 15:33:42.832: Failed to load module "canberra-gtk-module"` (though this did not prevent me from using the VoTT app)

**Comment by aribornstein** [comment]
Strange does it work if you install and run from npm?

**Comment by Smarker** [comment]
I also tried to also run with npm, but got the same error messages.

**Comment by Smarker** [comment]
Closing, since using the running the latest release `1.6.1` `vott_linux.snap` solves this issue.

**Comment by rbavery** [comment]
I'm using the preview 3 release of 2.0 and I still get the warning 

`Gtk-Message: Failed to load module "canberra-gtk-module"`

even though this it is installed. I ran `sudo apt-get install libcanberra-gtk*` following this thread: https://www.linuxquestions.org/questions/linux-software-2/gtk-message-failed-to-load-module-canberra-gtk-module-936168/ 

and the warning message is the same
