### ISSUE TITLE
Shading in bounding box can make it difficult to see object

### ISSUE THREAD

**Issue by abfleishman** [Microsoft/VoTT#270]
The shading in the bounding box can make it difficult to see the object.  it would be nice to be able to control the transparency of the background shading or at the very least toggle it on and off (with a keyboard shortcut). this was partly addressed with #251 . the shading is better than the lines.

![image](https://user-images.githubusercontent.com/9219852/48085280-a1ce2180-e1ae-11e8-9bf4-3fbbafbec95e.png)

**Comment by kichinsky** [comment]
Added region box background toggling in #274. Use ctrl+B.
