### ISSUE TITLE
Export to Custom Vision doesn't work if you already have a maximum number of projects

### ISSUE THREAD

**Issue by stas-pavlov** [Microsoft/VoTT#278]
Hi!

At Paris ML OpenHack I tried to demo how you can build custom object detection service using Custom Vision and VOTT. I found that if you have maximum number of projects in your customvision.ai account, VOTT just doesn't export images with no user-friendly errors as it can't create a new project to export images.

It would be great to add at least basic user-friendly error handling for export for Custom Vision Service.

Thanks,
Stas

**Comment by wbreza** [comment]
Resolved in v2.0.0
