### ISSUE TITLE
keyboard shortcut not working on ubuntu 16.04

### ISSUE THREAD

**Issue by DimitriF** [Microsoft/VoTT#299]
Hello,
The keyboard shortcut don't seems to do anything under ubuntu 16.04
I used the version v1.8.7.
Dimitri

**Comment by wbreza** [comment]
@DimitriF - which keyboard shortcut are you referring to? Or all of them?

**Comment by DimitriF** [comment]
Hello,
the number keys are the one I would really use, in addition, I just tested the other presented in the README:

1. Working: ctrl+O, ctrl+I, ctrl+S, ctrl+E,ctrl+space, ctrl+D ; D, ctrl+C, ctrl+X, ctrl+V, dir(next/previous image)

2. Not working: 
- ctrl+T (Console said: Cannot read property 'stopTracking' of undefined), 
- ctrl+N, no effect
-  shift+Del, no effect but may be just for video
- ctrl+H,  no effect
- number keys, no effect
- ctrl+dir (region manipulation); ctrl+alt+dir; wctrl+shift+dir

3. Unsure, not applicable: ctrl+A, space

I may have forgotten one or two.

**Comment by DimitriF** [comment]
Hello, 
I gave it another try but this time, I downloaded the linux AppImage (V 1.7.2) and it worked as intended. Previously, I took a  zip file which looked like V 1.5.0 (VoTT-linux-x64.zip; with inside a version file saying 1.8.7).
