### ISSUE TITLE
tag label covers object in small boxes

### ISSUE THREAD

**Issue by abfleishman** [Microsoft/VoTT#302]
The tag label covers the object I am drawing the bounding box around when it is small. 
This is in dev version
Could solve by toggling the label somehow 
![image](https://user-images.githubusercontent.com/9219852/48524263-945f0a00-e834-11e8-8627-919896b794bb.png)

**Comment by kichinsky** [comment]
Hi, I adjusted how toggling background works (ctrl+b) (not in dev yet):
![image](https://user-images.githubusercontent.com/979457/48545458-038d3a80-e8d7-11e8-9f40-eb93135e30c3.png)
![image](https://user-images.githubusercontent.com/979457/48545488-1142c000-e8d7-11e8-9e8e-0f60a7864cc9.png)

Does it solve the issue?

**Comment by abfleishman** [comment]
@kichinsky Yes I think that toggling the background works!  Thanks!
