### ISSUE TITLE
Label points instead of bounding boxes

### ISSUE THREAD

**Issue by abfleishman** [Microsoft/VoTT#303]
VoTT is becoming incredibly useful! A use case I could see that ties into #245 is instead of bounding boxes on a click you could just tag a point (single x/y coordinate) (think of it as a centroid of some polygon) and then you could later just buffer your point (think of aerial images where you are taking pictures of similar-sized things or an image where the things you are trying to put a box around are only a few pixels anyway. 
The attached photo once I had some boxes on here I had trouble seeing the birds that are next to already tagged birds). So just laying down points could make tagging this easier.
![image](https://user-images.githubusercontent.com/9219852/48524673-2adffb00-e836-11e8-9ce5-7dc03d4da0df.png)

**Comment by kichinsky** [comment]
Adressed in #374. We have now new point region type (with zero width and height, not resizable).

Also with the locking feature it should be now easier to see/tag close regions.

_p.s. We don't have exporter that support points, so all points are treated as boxes now._
