### ISSUE TITLE
Custom exporting settings

### ISSUE THREAD

**Issue by kichinsky** [Microsoft/VoTT#308]
A request from the CSE OneWeel sync-up: 
* Allow precise settings on what and how is exported (all images, only tagged images, sampling % etc). 
* Custom options/UI for each exporter (e.g. change labels and input fields based on chooses exporter).

**Comment by wbreza** [comment]
@kichinsky - this is on the roadmap.  We are thinking to wrap up the export types as their own providers which would include a JSON schema for the export options that would allow us to dynamically render a form as well as a simple interface that can be implemented to handle the logic for the desired export format.

**Comment by wbreza** [comment]
Resolved in v2.0.0
