### ISSUE TITLE
Template box resizing

### ISSUE THREAD

**Issue by abfleishman** [Microsoft/VoTT#319]
Relates to #245 
Sometimes a drone flight will be at 100m and other times at 150m.  within a flight, a type of object will be the same size, but between flights, they might be different sizes due to flight height. 

If a photo pull includes images from two flights with different heights you may want to be able to switch sizes quickly.  

I think you could have a template and then it there was a quick way to change the size (expand equally in all directions) that would be really useful. 

IDEA: when in template tool, use "-" and "+" to add 5 px to size of bbox template.

**Comment by kichinsky** [comment]
In #338 I added mouse wheel support for template tool. Use **shift + wheel** to increase/decrease template size. I'm using a multiplayer (1.1) as of now.

**Comment by kichinsky** [comment]
I was playing around with scroll, and will make another adjustment in the next update for the template-tool (all preserving proportion):

- **Mouse whell** -- additive change of size (+1px and -1px);
- **Shift + wheel** -- multiplicative change of size (*1.1 and /1.1).

**Comment by kichinsky** [comment]
Should be adressed now in #341
