### ISSUE TITLE
Label toolbar maxed out

### ISSUE THREAD

**Issue by abfleishman** [Microsoft/VoTT#320]
There is a limit to the number of labels that can be added to the toolbar (see screenshots).  There are labels in the list at the initial configuration that do not show up.  

IDEA: be able to scroll down the labels if there are too many to disply
IDEA: be able to "filter" by typing the beginning of a label and only keep labels that have those letters in that order

<img width="1209" alt="screen shot 2018-11-26 at 21 22 42" src="https://user-images.githubusercontent.com/9219852/49060264-a2f8da00-f1c1-11e8-9aac-3bc268c92cc6.png">
<img width="565" alt="screen shot 2018-11-26 at 21 22 56" src="https://user-images.githubusercontent.com/9219852/49060266-a4c29d80-f1c1-11e8-89bf-59f31efaed27.png">

**Comment by Blajimir** [comment]
I had the same problem and I solved it. 
In the file **VoTT-1.6.1/src/public/js/video-tagging/video-taggingstyles.html** add in class optionalTags two lines following below :
_overflow-y: scroll;
height: 100px;_
In this way you get something like this:
```
.optionalTags {
	float: left;
	width: 85%;
	margin: 1em 0 0 1.5em;
	overflow-y: scroll;
	height: 100px;
}
```
After all you must restart your application. If you are using a "binary" version application, use the following command: "npm run dist: winlinux" (Windows or Linux) or "npm run dist: mac" (Mac OS) to create your application. The application of the new version will appear in the folder calls "dist" (**VoTT-1.6.1/dist**)

**Comment by Legor** [comment]
@Blajimir  i took your solution in a slight different way and added it as PR. I used overflow-y: auto instead, so that the scrollbar is only displayed if needed. Also, the styles are in a separate css file and not in the html anymore.
