### ISSUE TITLE
Minimum bounding box size too large 

### ISSUE THREAD

**Issue by abfleishman** [Microsoft/VoTT#334]
The minimum size of the bounding box is too large and even when drawn smaller it defaults to a new bigger size.

**Comment by abfleishman** [comment]
Here is an example of an image I would like to tag with small bounding boxes around the blurry little black birds (Tufted Puffins)
![p9990066_912_2052](https://user-images.githubusercontent.com/9219852/49273334-7810bf00-f429-11e8-974c-35df2c520767.JPG)

**Comment by kichinsky** [comment]
@abfleishman should we remove the minimum size at all or make it smaller?

**Comment by kichinsky** [comment]
I will take some pause to think around some better options to edit small boxes (without zooming being implemented).

**Comment by kichinsky** [comment]
Hey, I reduced the threshold for new box size from 20 to 5px in #341. Let's see whether it works better.

Also the points support is comming soon, so it could be also a good alternative if you need just points (with some bounding box for export). But points are not editable in size.
