### ISSUE TITLE
Key Shortcuts Broken

### ISSUE THREAD

**Issue by aribornstein** [Microsoft/VoTT#337]
Hi @kichinsky @PIC123  in the master branch I can no longer remove a selected tag with with the delete key. I can also no longer drag or resize bounding boxes or cycle through boxes with the tab key.

**Comment by aribornstein** [comment]
Also holding the ctrl key leaves three bounding boxes 
![image](https://user-images.githubusercontent.com/3045407/49338992-1754d280-f633-11e8-93df-4689aaf5dd2e.png)

**Comment by aribornstein** [comment]
And the copy and paste shortcuts don't work.

**Comment by kichinsky** [comment]
I will check today. Seems like I broke something with shortcuts management.

Also maybe we should consider adding hot keys related tests.

**Comment by kichinsky** [comment]
@aribornstein Sorry, I can't reproduce any of that on my build. Can you check it with my latest PR? #338

What about other shortcuts? E.g. R and T keys to switch selection mode, L to lock regions?
