### ISSUE TITLE
Auto-apply tags for new regions based on some setting

### ISSUE THREAD

**Issue by aribornstein** [Microsoft/VoTT#344]
![image](https://user-images.githubusercontent.com/3045407/49478730-4896f380-f829-11e8-9419-ccc3939256fc.png)

Instead of having to hit the 1 or 2 key over and over again i think it would be nice if the box changed color for a selected tag that can  be toggled with the numerical keys additional tags can still be added when a box is selected

**Comment by aribornstein** [comment]
@kichinsky

**Comment by kichinsky** [comment]
Added p.2 with marking tags for auto-applying in #341.

**Comment by kichinsky** [comment]
Related to #321

**Comment by kichinsky** [comment]
@aribornstein it should be now in master.
