### ISSUE TITLE
Add version number somewhere in the app

### ISSUE THREAD

**Issue by abfleishman** [Microsoft/VoTT#347]
I would like to be able to see what version of VoTT I am using somewhere in the app. Specifically, I am talking about the release version that I downloaded and installed.  Like a little "About" menu item that many software have.

**Comment by kichinsky** [comment]
Related to #298, #297, #296 :)

**Comment by Legor** [comment]
Vote to close this .. didnt mention the close in original PR version and updating the PR with _close_ doesnt seem to work afterwards.
