### ISSUE TITLE
Can VoTT be used to annotate ocr task

### ISSUE THREAD

**Issue by northeastsquare** [Microsoft/VoTT#419]
Hello, can VoTT be used to annotate image with box and line words for OCR tasks?

**Comment by kichinsky** [comment]
Do you mean adding custom text for each box instead of a tag?

**Comment by northeastsquare** [comment]
@kichinsky Yes, can it?

**Comment by northeastsquare** [comment]
As  I test the exe, currently NO.

**Comment by kichinsky** [comment]
Yeah, it is not supported. I you need that feature in future, please, reopen the issue or submit a new one. I think we can work on that.
