### ISSUE TITLE
Reload whole label work on another pc

### ISSUE THREAD

**Issue by lightning20** [Microsoft/VoTT#427]
To check the accuracy of the labels from another PC, is it possible to open the label works in another PC.  In the same PC, the label of the video can be reloaded and played again. But not sure how to open in another PC, thanks.

**Comment by kichinsky** [comment]
Can you copy the .json file generated by VoTT to another PC? Ususally it has the same name as the video file.

**Comment by wbreza** [comment]
@lightning20 - Yes, the json file is saved along side the video file.  These can be copied to another computer and then opened.
