### ISSUE TITLE
Ubuntu14.04 Install Errors occur happen

### ISSUE THREAD

**Issue by HoracceFeng** [Microsoft/VoTT#501]
Hi, thanks for the work firstly. I have tried the version 1.5 in Ubuntu14.04, everything's nice. But when I try install version 1.7.1 in Ubuntu14.04, errors occur like this:

For .Appimage:
![appimage](https://user-images.githubusercontent.com/20824041/51578974-4a606780-1efa-11e9-8ab3-469c814e1e81.png)
I have do some search, it seems like a version mismatch, I guess it may because version 1.7.1 need a higher version of libdbus in maybe Ubuntu 16 or higher.

For npm install:
![npminstall](https://user-images.githubusercontent.com/20824041/51579111-b773fd00-1efa-11e9-8de9-5394335da90d.png)
Not sure why this error would happen...

For .snap：
I do install from snap successfully, but I cannot find out ways to open the installed app... either enter 'vott' in command line or search it via the 'application' not work.

Waiting for help ...

**Comment by mydiemho** [comment]
we have released version 1.7.2, could you try and let us know if you're still having problems?

**Comment by HoracceFeng** [comment]
@mydiemho thank you, it works.
