### ISSUE TITLE
Was the Export interface deprecated?

### ISSUE THREAD

**Issue by aribornstein** [Microsoft/VoTT#529]
**Is your feature request related to a problem? Please describe.**
Export interface for adding new export formats to the tool.

**Describe the solution you'd like**
In the case that new formats are created. Developers should be able to support them through an exporter interface so that users don't have to worry about writing custom scripts to transform their data from the VoTT Json format.

**Comment by wbreza** [comment]
@aribornstein The export interface has not been deprecated, but extended!  Export providers now support custom UI fields to configure relevant fields within the export provider.  All project export options are availalble in the export area.

![image](https://user-images.githubusercontent.com/6540159/52220485-dad06d80-2853-11e9-8533-02894cc09282.png)
