### ISSUE TITLE
about packaging into exe files

### ISSUE THREAD

**Issue by kurmanadhvalla** [Microsoft/VoTT#537]
I  modified some of the code  and  now I want to package it into exe . How exactly I can do ? It is more of a question not an issue. I am new to node and electron. someone please help me out.

**Comment by wbreza** [comment]
What branch are you working off of? `maste`r (v1) or `v2`?

**Comment by kurmanadhvalla** [comment]
@wbreza I am working on v1

**Comment by wbreza** [comment]
@kurmanadhvalla - If you have cloned the source you can run the NPM scripts to build the distributions.

See https://github.com/Microsoft/VoTT/blob/master/package.json#L10 for more info

`npm run dist:winlinux` or `npm run dist:mac`
