### ISSUE TITLE
V2 Preview-1 OSX "Refresh Application" doesn't work AB#17058

### ISSUE THREAD

**Issue by alancast** [Microsoft/VoTT#559]
**Describe the bug**
In version 2.0.0-preview1 OSX, when clicking on the "Refresh Application" button in settings the app just goes to a blank white screen

**To Reproduce**
1. Open VoTT (I have no connections created and no local projects, it was my first time installing VoTT)
2. Click on the settings gear in the lower left corner
3. Click the "Refresh Application" button on the right hand side

**Expected behavior**
Unclear, but I was anticipating going back to the home screen or something with no projects there

**Screenshots**
![image](https://user-images.githubusercontent.com/3934092/52598595-18606800-2e0b-11e9-90c2-6e7dcfec96de.png)
![image](https://user-images.githubusercontent.com/3934092/52598602-1eeedf80-2e0b-11e9-8af3-5a423b8adeb3.png)

**Platform**
[ ] Electron
[ ] Browser
Neither, v2 is React

**OS**
[ ] Windows
[x ] Mac
[ ] Linux

**Additional context**
I don't have any projects setup yet, so this perhaps might not happen if projects are setup.

**Comment by wbreza** [comment]
@alancast - This is a bug.  The application should refresh the current window.

**Comment by wbreza** [comment]
Resolved with #629.  Released with Preview 2
