### ISSUE TITLE
V2 Preview-1 In app error messages for creating a new project without connections AB#17057

### ISSUE THREAD

**Issue by alancast** [Microsoft/VoTT#561]
**Is your feature request related to a problem? Please describe.**
My first time downloading VoTT I went to create a new project but was unsuccessful because I hadn't created connections before attempting to create the new project. I did see that in the documentation it said that connections were required to create a new project, but I didn't see that until after the fact. Currently when I just create a new project without any connections I click "Save Project" and nothing happens. 

**Describe the solution you'd like**
It would be nice if an error message came up saying that connections are required to create a project (similar to how one comes up if you try to create a project without a name)

**Describe alternatives you've considered**

**Additional context**
Even though it does say it's required in the documentation, I read through all the documentation before playing around with it and still got stumped (it's tough to remember all of the details). It's also safe to say a decent portion of folks will not read the documentation at all.

**Comment by wbreza** [comment]
Thanks for your feedback @alancast. This is a bug.  An error message should display when you attempt to create a new project without selecting a source & target connection.

**Comment by wbreza** [comment]
This has been released as part of Preview 2
