### ISSUE TITLE
V2 Preview - Quick labeling not working

### ISSUE THREAD

**Issue by JCAAUSFRA** [Microsoft/VoTT#572]
In previous versions of VoTT you could add tags by pressing numbers (ie. 1, 2, 3 etc). In this new version (V2) I have to click the tag to get a positive tag. 

good feature to add to V2

**Platform**
[ *] Electron
[ ] Browser

**OS**
[* ] Windows
[ ] Mac
[ ] Linux

**Comment by wbreza** [comment]
@JCAAUSFRA  - Thanks for the feedback.  We are still finalizing our accelerator / hot key strategy but in the current preview release you can use `Ctrl+{number}`.

**Comment by wbreza** [comment]
In Preview 2 this has been migrated back to single number quick labeling.
