### ISSUE TITLE
V2 Preview - Quick Square fuction not in V2

### ISSUE THREAD

**Issue by JCAAUSFRA** [Microsoft/VoTT#573]
In previous versions there was a function where you could scroll and create a square around the desired region. you could then adjust the size of the square by pressing ctrl and scrolling. This was very useful.

**Comment by wbreza** [comment]
Thanks for the feedback @JCAAUSFRA  - by the end of our v2 development cycle we plan to achieve parity with the most used/wanted features that currently exist in v1

**Comment by wbreza** [comment]
This feature will be complete with our Preview 3 release.

**Comment by wbreza** [comment]
Resolved with #651

**Comment by wbreza** [comment]
Feature is available within v2 Preview 3
