### ISSUE TITLE
V2 Preview-Paste SAS broken for Mac

### ISSUE THREAD

**Issue by xinyi-joffre** [Microsoft/VoTT#652]
**Describe the bug**
On Mac OS, VOTT v2 Add Blob Connection page does not allow paste for SAS.

I am using latest build of v2 (v2.0.0 Preview 1)

**To Reproduce**
Copy the SAS from portal and make sure it is in your clipboard (can paste into other places okay).
Try to paste into SAS field of Add Blob Connection using CMD-V or CTRL-V (both do not work).
The field is still blank.

**Expected behavior**
Value is pasted into SAS field using CMD-V.

**Platform**
[X] Electron
[ ] Browser

**OS**
[ ] Windows
[X] Mac
[ ] Linux

**Comment by wbreza** [comment]
Resolved in v2.0.0
