### ISSUE TITLE
Can't draw new box

### ISSUE THREAD

**Issue by abfleishman** [Microsoft/VoTT#674]
**Describe the bug**
After a few frames, I was not able to create a new bounding box in version 1.7.2.

**To Reproduce**
I added bounding boxes to 3 images and then it stopped letting me. I think it happened when I pressed the down key to move to the next image in V2 prev2.  I am now having the same issue on my local hard drive and a shared drive on our network.
 when I opened the dev console in V1.7.2 there was an error (see screenshot). but I didn't see any error is v2prev2.
**Expected behavior**
I should be able to keep adding bounding boxes
**Screenshots**
![image](https://user-images.githubusercontent.com/9219852/54227251-c0c22480-44bc-11e9-8ee3-aa69b078d9cc.png)

**Platform**
[X] Electron
[ ] Browser

**OS**
[X] Windows
[ ] Mac
[ ] Linux

**Additional context**
This was a newly initialized project

**Comment by abfleishman** [comment]
I am actually having this issue on V2 preview 2 as well, but no error is being thrown.  I have the draw rectangle tool selected and it is not letting me draw.  
I am wondering if this is because the images are in a shared directory on the network rather than on my hard drive?

**Comment by abfleishman** [comment]
if I hover over an existing bounding box I get the ability to draw a new box back again

**Comment by haroutisonfire** [comment]
Make sure you're using the late nodejs version I fixed this issue by upgrading from v8 to nodejs v10.

**Comment by abfleishman** [comment]
@haroutisonfire is that needed even when using the compiled release version of VoTT?

**Comment by abfleishman** [comment]
I updated nodejs and it still has the same problem with 1.7.2

**Comment by wegel** [comment]
Same thing for me: can't add new boxes after a few (~3). Fiddling with an existing box brings back the functionality for a single new one, then stops again. This is on 1.7.2.

**Comment by abfleishman** [comment]
@wegel if you figure out what is happening I would really like to know.  I have rolled back to 1.7.1 which is not ideal.

**Comment by abfleishman** [comment]
I just downloaded and tried v2.0.0 preview 3 and still could not draw boxes after making ~4 new boxes.

**Comment by wbreza** [comment]
@abfleishman - Regarding the images you are tagging is there anything remarkable about them? Large file size? Large dimensions?  Are you able to share any images with us for review?

**Comment by abfleishman** [comment]
@wbreza I have tried a few different folders with different files (all jpgs). They were not huge ~4000x3000 but some were smaller (800x600). not giant files.  And I have tagged similar images with previous versions. with no issues. I can share images, what is the best way to share?  just post them here or???

**Comment by wbreza** [comment]
@abfleishman Feel free to email me. wallace.breza@microsoft.com.  We'll get to the bottom of this.  It's very strange that it is occurring on both 1.7.2 and v2 preview.

**Comment by kichinsky** [comment]
Hey, some news:
1. I was able to reproduce it on 1.7.2. In short, it is something around CanvasTools editor staying on the same state as it was on the previous frame (e.g., before switching to the next frame you holded pointer over a region, so the crossing line were hidden, and when you switched to the next frame it continued to be hidden). But I didn't test it on v2 preview so far.
2. The 1.7.2 is based on the vott-ct 2.1.4, I have a build using 2.1.17 and it does not have that issue. I will look into upgrading it further to 2.1.28 (or 2.2.0-beta) as latest version and then will submit a new PR.
3. I don't have a specific `reset()` method to reset the editor to initial state, but calling the `editor.AS.enable()` method on it should fix the problem (so for 1.7.2 it should be `videotagging.editor.areaSelector.enable()` from the console).

**Comment by wbreza** [comment]
Resolved with v2.0.0
