### ISSUE TITLE
TensorFlow Pascal VOC XML generation in v2

### ISSUE THREAD

**Issue by kurmanadhvalla** [Microsoft/VoTT#685]
**Describe the bug**
Generated XML do not have info about bounding boxes in v2

**To Reproduce**
Export in TensorFlow Pascal VOC format in v2

**Expected behavior**
Generated xml should have bounding boxes data
**Screenshots**

**Platform**
[ ] Electron
[ ] Browser

**OS**
[ ] Windows
[ ] Mac
[ ] Linux

**Additional context**

**Comment by wbreza** [comment]
@JacopoMangiavacchi - Can you please review.

**Comment by JacopoMangiavacchi** [comment]
Thank you @kurmanadhvalla.  Yes this is a regression bug.  We're investigating on this and planning for a fix.

**Comment by wbreza** [comment]
This issue has been resolved and will be included in upcoming release this week.
