### ISSUE TITLE
V2 Project Sample JSON

### ISSUE THREAD

**Issue by Walkeras** [Microsoft/VoTT#687]
Hello,

This is kind of a 2 part question: 

Does V2 currenlty have the ability to do the active learning if the parameters of where the model is located, and where the folder that is outputted is also located (or the endpoint) are in the projects JSON file?

And would we be able to get a copy of a complete schema so that we can edit the project our selves and add in the Active Learning component before the page has been completed to input the locations.

**Comment by wbreza** [comment]
@Walkeras - We don't have the ability to support a custom active learning model at this time but this feature is in the works.  We'll be starting with support for a generic model that supports over 90 domains but soon after we will support a BYOM (bring your own model) to help accelerate active learning efforts.

Regarding v2 schema - we don't have a JSON schema published at this time but the TypeScript interfaces for all the models is available @ https://github.com/Microsoft/VoTT/blob/v2/src/models/applicationState.ts#L102
