### ISSUE TITLE
V2 Preview2 - Pascal VOC ImageSets txt files contain duplicates with opposite values (-1, 1)

### ISSUE THREAD

**Issue by glenvorel** [Microsoft/VoTT#692]
**Describe the bug**
When the user exports project as *Tensorflow Pascal VOC*, the generated txt files in ImageSets\Main folder list each image multiple times, often with a mixed values of `1` and `-1`.

Example: content of the file `cat_train.txt`:
```
cat_image_01.jpg -1
cat_image_01.jpg 1
cat_image_02.jpg 1
cat_image_03.jpg -1
cat_image_02.jpg 1
cat_image_03.jpg 1
```

**To Reproduce**
Label multiple images with multiple tags and then export as *Tensorflow Pascal VOC*.

**Expected behavior**
Each image should appear in the ImageSets txt file only once with the value of `1` if the image contains the class and `-1` if it does not.

**Platform**
[x] Electron
[ ] Browser

**OS**
[x] Windows
[ ] Mac
[ ] Linux

**Comment by wbreza** [comment]
@JacopoMangiavacchi - Can you please review.

**Comment by wbreza** [comment]
This issue has been resolved and will be in upcoming release this week.
