### ISSUE TITLE
opening a cloud project results in a window with dead buttons

### ISSUE THREAD

**Issue by rbavery** [Microsoft/VoTT#722]
![Selection_022](https://user-images.githubusercontent.com/22258697/55522037-2460ed00-5638-11e9-9c6e-4e2dfabfc80c.png)

when I click on the green "Ok" button or the "Go Back" button nothing happens. I can get the window to go away by selecting the x in the upper right. I'm using Ubuntu 18, v2 preview 3

**Comment by wbreza** [comment]
Before you can open cloud project you will need to have 1 or more cloud connections defined.  Please create a cloud connection then you can use this feature to browse projects in that connection.
