### ISSUE TITLE
Open folder for images...error in console, blank page after setting up tagging configuration.

### ISSUE THREAD

**Issue by kmansel** [Microsoft/VoTT#723]
**Describe the bug**
There seems to be some error when selecting a folder for image tagging on MacOS Mojave 10.14.3  I get passed the object tagging configuration and the screen is blank.

**To Reproduce**
- Launch VoTT application via "node start"
- Select image option
- Select folder of images
     - Error present in console at this time...

```
objc[48619]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff9ecdb210) and /System/Library/
PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x11da4bdc8)
. One of the two will be used. Which one is undefined.
```

- Input tagging configuration
- ***blank screen***

**Expected behavior**
Expected to bring up the images and start tagging?

**Screenshots**
![image](https://user-images.githubusercontent.com/1252780/55531637-fa232580-565f-11e9-8d2f-9819fa2d27b9.png)

![image](https://user-images.githubusercontent.com/1252780/55531692-19ba4e00-5660-11e9-8a4d-b2ae362e66c9.png)

![image](https://user-images.githubusercontent.com/1252780/55531946-df04e580-5660-11e9-9f8e-34ccbb493a93.png)

![image](https://user-images.githubusercontent.com/1252780/55531753-41a9b180-5660-11e9-8105-c745a77511f6.png)

![image](https://user-images.githubusercontent.com/1252780/55531829-82092f80-5660-11e9-93d5-3895add9164f.png)

**Platform**
[X] Electron
[ ] Browser

**OS**
[ ] Windows
[X] Mac
[ ] Linux

**Additional context**

**Comment by wbreza** [comment]
@kmansel Do you experience this on the published release or just building and running the source?  Please also give it a try on our new v2 version.
