### ISSUE TITLE
V2 - No CNTK Export

### ISSUE THREAD

**Issue by JCAAUSFRA** [Microsoft/VoTT#754]
Hi Noticed the new V2 does not have the CNTK export. Is this something that is in the pipeline?

**Comment by wbreza** [comment]
Thanks for the feedback.  Leading up to the v2 release we had prioritized other export providers above CNTK.  As long as there is enough interest we can increase the priority of this feature.

**Comment by skywalkerisnull** [comment]
I also need the CNTK export option in V2

**Comment by wbreza** [comment]
@JCAAUSFRA @skywalkerisnull - Would you be able to help test the CNTK export in v2?  Code has been merged into `develop` branch.  If all is good will be included in the next patch/minor release.

**Comment by skywalkerisnull** [comment]
I will download it over the weekend and give it a go.

**Comment by JCAAUSFRA** [comment]
I'm in to

**Comment by skywalkerisnull** [comment]
Hey @wbreza I cloned the latest version of the `develop` branch and was able to sucessfully export the CNTK. I will need to tag a few more images and then run a really quick model through CNTK when I am back infront of the workstation. But otherwise looks promising.

**Comment by cinis77** [comment]
CNTK export works bit fuzzy. It does not give correct export
