### ISSUE TITLE
add support other regions of custom vision service

### ISSUE THREAD

**Issue by guybartal** [Microsoft/VoTT#759]
please add support for other regions of custom vision service apart from south central us,
currently it's hard-coded and it's not that informative...
I've discovered that only by enabling developer mode.

**Comment by wbreza** [comment]
Yes, you are correct.  We will extend the custom vision export provider template to include a region dropdown for the newly added regions.

**Comment by wbreza** [comment]
Hi @guybartal - This change has been added and will be included in the next release.  Feel free to try it out in the `develop` branch.
