### ISSUE TITLE
Unjust "Invalid region(s) detected" when I moved from beta 3 to v2.0.0

### ISSUE THREAD

**Issue by marchage** [Microsoft/VoTT#767]
Hi,

I get "Invalid region(s) detected" modal which prevents me from going to the next image. VoTT is complaining that I have one or more regions not tagged in this asset. But this is not the case. At least not intentionally/that I am aware of. This behaviour started with the transition from v2.0.0-preview.3 to v2.0.0.

Ah men! I should have notified you earlier: I deleted some video's and those actually are still present in the gui with the notification "Unable to load asset". If I now open up the console I get a "Failed to load resource:" which is entirely justified. But still, it's not all the time, and not always on the same image or missing video resource that the modal starts fighting me and I have to browse away to a different menu item (home, project settings, whatever) and then open the project again (which seems to be my workaround). 

I am using the mac version. Mac is up to date & updated at Apple's convenience.
Reproduce? Haven't tried that from the ground up, sorry, but:
- tag few hundred image with version v2 beta3 using the polygon _and_ rectangle tool in the same image.
- upgrade to v2.0.0
- browse around a bit through your taggings and 
- behold...!

Hope this helps, Marc

**Comment by wbreza** [comment]
Hi @marchage. Thanks for the feedback.

Regarding the "Invalid region(s) detected" message - this was a new feature added in the final release.  There may be a very small region accidentally added.  If you open the `.vott` project file in your favorite text editor you should be able to find the asset id of the invalid asset.  From there you can open the `{assetId}-asset.json` and find and remove the untagged region(s).

This may be an opportunity for a feature to provide an option to auto remove invalid regions within the same warning dialog.

Regarding assets that you have removed - Again you can manually remove these from the project file which would avoid them getting loaded in the UI.

Again - an opportunity here would be to provide a feature to remove an asset from the project that either no longer exists or you may want to appear hidden.

**Comment by wbreza** [comment]
Closing for now.
