### ISSUE TITLE
clicking help button while viewing settings page and dev toolbar is open, the help lightbox blocks the app

### ISSUE THREAD

**Issue by guybartal** [Microsoft/VoTT#768]
clicking help button while viewing settings page and dev toolbar is open, the help lightbox blocks the app:

![image](https://user-images.githubusercontent.com/3179107/56240669-bd622000-609c-11e9-8507-e64338334270.png)

**Comment by wbreza** [comment]
Hi @guybartal - I'm not following.  The help dialog does block the app when activated, but when you dismiss the dialog the app should return to previous state.

I do see that it appears that you have an "export" in progress based on the toast message displaying.  If you exit the toast message the "X" should then be available to close the help dialog.

**Comment by guybartal** [comment]
you are correct, my mistake... toastr hides the X button...
