### ISSUE TITLE
Export to CustomVision service works only for Classification

### ISSUE THREAD

**Issue by michalmar** [Microsoft/VoTT#770]
I was not able to export to CustomVision for Detection - it ends up in classification regardless of project type selection

**Comment by michalmar** [comment]
I was not able to export to CustomVision for Detection - it ends up in classification regardless of project type selection

**Comment by wbreza** [comment]
Hi @michalmar.  Right now the `domain` dropdown contains domains for both classification projects and object detection projects.  The 2nd half of list starting at `General` are object classification domains.  Please try selecting one of these in combination with `Object Detection` project type and it should work as expected.

We're working on cleaning this up so it is more clear.

**Comment by michalmar** [comment]
thanks @wbreza! I just missed that there are two `General` domains while the first leads to Classification and the second to Detection. It is working now!

**Comment by wbreza** [comment]
Domain list now filtered with #765
