### ISSUE TITLE
Broken local project file

### ISSUE THREAD

**Issue by golee** [Microsoft/VoTT#776]
Can't open project file (*.vott)
Some closing curly brackets are omitted 
about end of the file.

![image](https://user-images.githubusercontent.com/1129665/56412034-da296e00-62bd-11e9-8489-6a0efbedd477.png)

**Comment by wbreza** [comment]
@golee Thanks for reporting this.  We have not seen this in any of our testing over the past few months leading up to the new release.  Can you give us some more information?  What platform are running on?  Can you easily reproduce this?  What are the steps?

**Comment by golee** [comment]
@wbreza 
OS: Windows 10

You can reproduce this by insert some letter which size is larger than 1 byte at Connection Display Name. Save the project and then 'Open Local Project' from project file (*.vott)
e.g. 😂, 코트, 漢

![image](https://user-images.githubusercontent.com/1129665/56778134-d642a200-680f-11e9-97d8-21858ae2a5fc.png)

**Comment by wbreza** [comment]
Thanks for the information @golee  - We will review your pull request.

**Comment by Tiddl1991** [comment]
We are having the same issue here, are there any updates?

**Comment by wbreza** [comment]
Resolved in `v2.1.0`
