### ISSUE TITLE
Invalid Region detected (One or more regions have not been tagged) 

### ISSUE THREAD

**Issue by patricieni** [Microsoft/VoTT#784]
I'm trying to tag some images and I cannot move to the second image because of this message. Attached  is a screenshot. 
![Screen Shot 2019-04-26 at 15 04 37](https://user-images.githubusercontent.com/3986917/56809694-cd17fc00-6834-11e9-88ec-8f48bc4cf3eb.png)

Any help is appreciated

**Comment by vidkr** [comment]
i am also getting the same error, any help appriciated. 
thank you
