### ISSUE TITLE
Feature Request: Project Settings - Auto Fill Tags

### ISSUE THREAD

**Issue by skywalkerisnull** [microsoft/VoTT#793]
Hello,

When we use the new active learning settings, it would be great if the tags used in the models are automatically propergated to the tags (or allow us to choose a subset of the tags to use) if they are known.

In addition, on the Active Learning page, it would be great to have a list of the tags/labels that are in that model (if known).

This way, we can ensure that we are using the same names (and not calling one "Kangaroo", and the other "kangaroos" etc.) and wonder why we aren't getting the correct returns.

**Comment by JacopoMangiavacchi** [comment]
Thank you for your feedback. You can find in this json file the list of all the classes supported by the default model trained on the Coco dataset: https://github.com/Microsoft/VoTT/blob/master/cocoSSDModel/classes.json

**Comment by skywalkerisnull** [comment]
Hello @JacopoMangiavacchi that is a good resource, but to then manually add in the tags can still have transcribing errors, miss tags, add in tags that you think are there but aren't etc. Having VoTT pull that automatically and presenting the list automatically would remove all those possible errors and allow for much faster startup of a project.

**Comment by JacopoMangiavacchi** [comment]
Hi @skywalkerisnull, thank you again for the feedback.  We discussed this internally and we think it is better to mantain the  current behavior of letting the active learning add label classes to the project one by one, while these are detected from each image passed to the AL detection.

We already provide a default model that support lots of generic classes and as this is activated by default in the project settings for any new project we want to avoid to import automatically in any new project all of these the classes.

**Comment by skywalkerisnull** [comment]
@JacopoMangiavacchi that could be solved by having a workflow that allows us to cherry pick the tags that we want to load from the model, or accept as a suggestion. This could also be used as a way to blacklist or prevent certain tags being suggested. i.e. we have a data set of vegetation (in Australia), and the built in model kept suggesting things like giraffe, car, and zebra. Whilst humorous and a good point to show some of our colleges what happens when you take a AI model into a new/different domain it was suggesting a lot of nonsense and added a lot of noise to the tagging.

Essentially, we have no control over what that model is going to predict (non-deterministic nature of AI) so we can't blindly trust that we won't get these false positives in any new domain, and loading the tags automatically provides us back some of that control.

Our use case of how we want to be able to use active learning as a way of loading very broad generic classification systems that allow us to hone in on the more specific data. i.e. Our core AI detects vegetation, it is fantastic at doing just that, but we want to build on that, and using the Active Learning will allow it to correctly detect vegetation, and then we can add an additional label saying what it detected is Harrisia Cactus, or Feathertop Rhodes etc.
