### ISSUE TITLE
TFRecord export .tfrecords for each image

### ISSUE THREAD

**Issue by stanlee321** [microsoft/VoTT#796]
**TFrecord export creates .tfrecords for each image**

When I want to export my project to .tfrecord format, it does the export for each image with extension `image_name_x.tfrecord`  instead of a big file  `data.tfrecord`.

**Steps to reproduce**
1. Go to 'export settings'
2. Click on ' Provider (TensorFlow records) '
3. Click on ' Asset State (Only tagged Assets) '
3. Click on  'Save Export Settings'
4. Click on 'Tags Editor Tab'
5. Click on 'Export Project'

**Expected behavior**

`$ ls <outputfolder> 
dataset.tfrecord
`

** Actual Output **

`$ ls <outputfolder> 
tf_label_map.pbtxt  thumb0052.tfrecord  thumb0104.tfrecord  thumb0156.tfrecord  thumb0208.tfrecord  thumb0260.tfrecord
thumb0001.tfrecord  thumb0053.tfrecord  thumb0105.tfrecord  thumb0157.tfrecord  thumb0209.tfrecord  thumb0261.tfrecord
thumb0002.tfrecord  thumb0054.tfrecord  thumb0106.tfrecord  thumb0158.tfrecord  thumb0210.tfrecord  thumb0262.tfrecord
thumb0003.tfrecord  thumb0055.tfrecord  thumb0107.tfrecord  thumb0159.tfrecord  thumb0211.tfrecord  thumb0263.tfrecord
thumb0004.tfrecord  thumb0056.tfrecord  thumb0108.tfrecord  thumb0160.tfrecord  thumb0212.tfrecord  thumb0264.tfrecord
thumb0005.tfrecord  thumb0057.tfrecord  thumb0109.tfrecord  thumb0161.tfrecord  thumb0213.tfrecord  thumb0265.tfrecord
thumb0006.tfrecord  thumb0058.tfrecord  thumb0110.tfrecord  thumb0162.tfrecord  thumb0214.tfrecord  thumb0266.tfrecord
thumb0007.tfrecord  thumb0059.tfrecord  thumb0111.tfrecord  thumb0163.tfrecord  thumb0215.tfrecord  thumb0267.tfrecord
thumb0008.tfrecord  thumb0060.tfrecord  thumb0112.tfrecord  thumb0164.tfrecord  thumb0216.tfrecord  thumb0268.tfrecord
thumb0009.tfrecord  thumb0061.tfrecord  thumb0113.tfrecord  thumb0165.tfrecord  thumb0217.tfrecord  thumb0269.tfrecord
thumb0010.tfrecord  thumb0062.tfrecord  thumb0114.tfrecord  thumb0166.tfrecord  thumb0218.tfrecord  thumb0270.tfrecord
thumb0011.tfrecord  thumb0063.tfrecord  thumb0115.tfrecord  thumb0167.tfrecord  thumb0219.tfrecord  thumb0271.tfrecord
thumb0012.tfrecord  thumb0064.tfrecord  thumb0116.tfrecord  thumb0168.tfrecord  thumb0220.tfrecord  thumb0272.tfrecord
thumb0013.tfrecord  thumb0065.tfrecord  thumb0117.tfrecord  thumb0169.tfrecord  thumb0221.tfrecord  thumb0273.tfrecord
thumb0014.tfrecord  thumb0066.tfrecord  thumb0118.tfrecord  thumb0170.tfrecord  thumb0222.tfrecord  thumb0274.tfrecord
thumb0015.tfrecord  thumb0067.tfrecord  thumb0119.tfrecord  thumb0171.tfrecord  thumb0223.tfrecord  thumb0275.tfrecord
thumb0016.tfrecord  thumb0068.tfrecord  thumb0120.tfrecord  thumb0172.tfrecord  thumb0224.tfrecord  thumb0276.tfrecord
thumb0017.tfrecord  thumb0069.tfrecord  thumb0121.tfrecord  thumb0173.tfrecord  thumb0225.tfrecord  thumb0277.tfrecord
thumb0018.tfrecord  thumb0070.tfrecord  thumb0122.tfrecord  thumb0174.tfrecord  thumb0226.tfrecord  thumb0278.tfrecord
thumb0019.tfrecord  thumb0071.tfrecord  thumb0123.tfrecord  thumb0175.tfrecord  thumb0227.tfrecord  thumb0279.tfrecord
thumb0020.tfrecord  thumb0072.tfrecord  thumb0124.tfrecord  thumb0176.tfrecord  thumb0228.tfrecord  thumb0280.tfrecord
thumb0021.tfrecord  thumb0073.tfrecord  thumb0125.tfrecord  thumb0177.tfrecord  thumb0229.tfrecord  thumb0281.tfrecord
thumb0022.tfrecord  thumb0074.tfrecord  thumb0126.tfrecord  thumb0178.tfrecord  thumb0230.tfrecord  thumb0282.tfrecord
thumb0023.tfrecord  thumb0075.tfrecord  thumb0127.tfrecord  thumb0179.tfrecord  thumb0231.tfrecord  thumb0283.tfrecord
thumb0024.tfrecord  thumb0076.tfrecord  thumb0128.tfrecord  thumb0180.tfrecord  thumb0232.tfrecord  thumb0284.tfrecord
thumb0025.tfrecord  thumb0077.tfrecord  thumb0129.tfrecord  thumb0181.tfrecord  thumb0233.tfrecord  thumb0285.tfrecord
thumb0026.tfrecord  thumb0078.tfrecord  thumb0130.tfrecord  thumb0182.tfrecord  thumb0234.tfrecord  thumb0286.tfrecord
thumb0027.tfrecord  thumb0079.tfrecord  thumb0131.tfrecord  thumb0183.tfrecord  thumb0235.tfrecord  thumb0287.tfrecord
thumb0028.tfrecord  thumb0080.tfrecord  thumb0132.tfrecord  thumb0184.tfrecord  thumb0236.tfrecord  thumb0288.tfrecord
thumb0029.tfrecord  thumb0081.tfrecord  thumb0133.tfrecord  thumb0185.tfrecord  thumb0237.tfrecord  thumb0289.tfrecord
thumb0030.tfrecord  thumb0082.tfrecord  thumb0134.tfrecord  thumb0186.tfrecord  thumb0238.tfrecord  thumb0290.tfrecord
thumb0031.tfrecord  thumb0083.tfrecord  thumb0135.tfrecord  thumb0187.tfrecord  thumb0239.tfrecord  thumb0291.tfrecord
thumb0032.tfrecord  thumb0084.tfrecord  thumb0136.tfrecord  thumb0188.tfrecord  thumb0240.tfrecord  thumb0292.tfrecord
thumb0033.tfrecord  thumb0085.tfrecord  thumb0137.tfrecord  thumb0189.tfrecord  thumb0241.tfrecord  thumb0293.tfrecord
thumb0034.tfrecord  thumb0086.tfrecord  thumb0138.tfrecord  thumb0190.tfrecord  thumb0242.tfrecord  thumb0294.tfrecord
thumb0035.tfrecord  thumb0087.tfrecord  thumb0139.tfrecord  thumb0191.tfrecord  thumb0243.tfrecord  thumb0295.tfrecord
thumb0036.tfrecord  thumb0088.tfrecord  thumb0140.tfrecord  thumb0192.tfrecord  thumb0244.tfrecord  thumb0296.tfrecord
thumb0037.tfrecord  thumb0089.tfrecord  thumb0141.tfrecord  thumb0193.tfrecord  thumb0245.tfrecord  thumb0297.tfrecord
thumb0038.tfrecord  thumb0090.tfrecord  thumb0142.tfrecord  thumb0194.tfrecord  thumb0246.tfrecord  thumb0298.tfrecord
thumb0039.tfrecord  thumb0091.tfrecord  thumb0143.tfrecord  thumb0195.tfrecord  thumb0247.tfrecord  thumb0299.tfrecord
thumb0040.tfrecord  thumb0092.tfrecord  thumb0144.tfrecord  thumb0196.tfrecord  thumb0248.tfrecord  thumb0300.tfrecord
thumb0041.tfrecord  thumb0093.tfrecord  thumb0145.tfrecord  thumb0197.tfrecord  thumb0249.tfrecord  thumb0301.tfrecord
thumb0042.tfrecord  thumb0094.tfrecord  thumb0146.tfrecord  thumb0198.tfrecord  thumb0250.tfrecord  thumb0302.tfrecord
thumb0043.tfrecord  thumb0095.tfrecord  thumb0147.tfrecord  thumb0199.tfrecord  thumb0251.tfrecord  thumb0303.tfrecord
thumb0044.tfrecord  thumb0096.tfrecord  thumb0148.tfrecord  thumb0200.tfrecord  thumb0252.tfrecord  thumb0304.tfrecord
thumb0045.tfrecord  thumb0097.tfrecord  thumb0149.tfrecord  thumb0201.tfrecord  thumb0253.tfrecord  thumb0305.tfrecord
thumb0046.tfrecord  thumb0098.tfrecord  thumb0150.tfrecord  thumb0202.tfrecord  thumb0254.tfrecord  thumb0306.tfrecord
thumb0047.tfrecord  thumb0099.tfrecord  thumb0151.tfrecord  thumb0203.tfrecord  thumb0255.tfrecord
thumb0048.tfrecord  thumb0100.tfrecord  thumb0152.tfrecord  thumb0204.tfrecord  thumb0256.tfrecord
thumb0049.tfrecord  thumb0101.tfrecord  thumb0153.tfrecord  thumb0205.tfrecord  thumb0257.tfrecord
thumb0050.tfrecord  thumb0102.tfrecord  thumb0154.tfrecord  thumb0206.tfrecord  thumb0258.tfrecord
thumb0051.tfrecord  thumb0103.tfrecord  thumb0155.tfrecord  thumb0207.tfrecord  thumb0259.tfrecord
`

**Desktop**
 - OS: Ubuntu 18.04.2 LTS
 - Browser Firefox
 - Version 66.0.3 (64-bit)

**Additional context**

It will be useful to get the split dataset feature like the Pascal VOC for TensorFlow Records and get two files `train.tfrecord` and `val.tfrecord`. Thanks for the support.

**Comment by JacopoMangiavacchi** [comment]
Hi @stanlee321  thank you for your feedback.  We decided to maintain backward compatibility with the way VoTT v1.x export data in this format because there are already many users with existing training pipelines in productions working this way with one tfrecord file per asset.

Anyway the internal code we have for persisting on file the tfrecord/protobuf data already support saving a list of images per single file.  

As VoTT is an open source project are you willing to contribute to implement the necessary changes in the UI to optionally support exporting all the assets in a single tfrecord file?

Eventually the source files to change to add this features are the tensorFlowRecords.ts and tensorFlowRecords.json in the src/providers/export/ folder.

**Comment by stanlee321** [comment]
Ohh I see, I just want to tell you that this is an amazing tool and have a lot of potential. 
Yes I can work on this feature.Thanks for getting me out of doubt.

**Comment by JacopoMangiavacchi** [comment]
Thank you in advance @stanlee321 for your contribution. We'll be super happy to review your PR for this feature request.

**Comment by DanielWicz** [comment]
There are any news on it?
