### ISSUE TITLE
`V1 to V2` conversion error

### ISSUE THREAD

**Issue by mveeris** [microsoft/VoTT#799]
**Describe the bug**
When opening any of my V1 projects I get error - "Asset not supported".
All my old projects work fine with version v1.8.4

**To Reproduce**
1. Open Local Project
2. Warning - "Are you sure you want to convert to v2 format?"
3. Error message as on screenshot

**Screenshots**
![image](https://user-images.githubusercontent.com/2188379/57335799-7233ae00-712c-11e9-90c1-048c2a3bdeac.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: 2.1.0

**Comment by wbreza** [comment]
@mveeris - The latest version for v1 is `1.7.2`.  Is this the version that you were using previously?  This error message only displays if there is an asset type within the project type that is not know.  Can you share your project file so we can review?

**Comment by mveeris** [comment]
@wbreza Thanks. I rechecked - ones I tested were last time were used with older version indeed. I now opened the same project file with 1.8.4 and saved. Now tried to open with 2.1.0 and there is new error.
![image](https://user-images.githubusercontent.com/2188379/57355378-8a301f80-7176-11e9-9d4d-6c5f18a21eb5.png)

Here is the same json file.
[Puit.txt](https://github.com/microsoft/VoTT/files/3155864/Puit.txt)

**Comment by wbreza** [comment]
@mveeris - I'm confused... There isn't a `1.8.4` version of VoTT.  `1.7.2` was the latest `1.x` version.  I'll assume for now you mean `1.7.2` and will take a look at your project file.

**Comment by mveeris** [comment]
@wbreza - Thanks.

**Comment by tbarlow12** [comment]
Closing for now, reach out if you need any further assistance
