### ISSUE TITLE
Generating config files from existing  Tensor Flow Pascal VOC xmls

### ISSUE THREAD

**Issue by kurmanadhvalla** [microsoft/VoTT#800]
I have xml files generated for dataset but they do not have corresponding .json files which vott needs.  Am I supposed to generate config files for those xml files to use them in vott ? If so,How can I proceed ? I s there any other  run around to render bounding boxes from xml ?

**Comment by wbreza** [comment]
Right now VoTT can only work with native VoTT projects, 1.x or 2.x.  Or you can load a project from a folder container `.tfrecord` files.  The v2 VoTT project format is pretty straight forward JSON that you can likely convert into from your XML.
