### ISSUE TITLE
Feature Request: Active Learning Authentication

### ISSUE THREAD

**Issue by skywalkerisnull** [microsoft/VoTT#821]
Hello,

The active learning via the custom URL really needs to have the ability to have authentication options.

i.e. tokens/keys and/or username/passwords

![image](https://user-images.githubusercontent.com/7260106/58995369-4a249100-8837-11e9-8ad9-4efd99712618.png)

We are not in the habit of having any of our models be publicly accessible without some form of authentication.

**Comment by JacopoMangiavacchi** [comment]
@skywalkerisnull thank you for your feedback. Completely understand your requirements but you may simply download the model locally and reference it directly from the local file system.   

I'm closing this issue for now but you are super welcome to collaborate on the implementation of this feature submitting a PR.  Thanks
