### ISSUE TITLE
Bug Report: Active Learning URL 

### ISSUE THREAD

**Issue by skywalkerisnull** [microsoft/VoTT#825]
The URL validator doesn't validate for a few different valid URLs, specifically if you use localhost, or an IP address (weather that is the local IP or a remote IP). Also if you specify the port number, it will fail to validate and save.

The following all fail to be validated:
```
http://localhost/v1/models/my_model:predict
https://localhost/v1/models/my_model:predict
http://127.0.0.1/v1/models/my_model:predict
https://127.0.0.1/v1/models/my_model:predict
http://127.0.0.1:5091/v1/models/my_model:predict
https://127.0.0.1:5091/v1/models/my_model:predict
http://192.168.2.45/v1/models/my_model:predict
https://192.168.2.45/v1/models/my_model:predict
http://192.168.2.45:5091/v1/models/my_model:predict
https://192.168.2.45:5091/v1/models/my_model:predict
http://fully.qualified.domain.io:5091/v1/models/my_model:predict
https://fully.qualified.domain.io:5091/v1/models/my_model:predict
```

**Comment by nansravn** [comment]
+1 on this issue. I'm trying to use for active learning a custom vision model that has been exported as a docker image. I have this model running with docker on the path http://127.0.0.1/image, but I can't use this locally hosted API for active learning. =/

**Comment by JacopoMangiavacchi** [comment]
@nansravn The current implementation of Active Learning functionality in VoTT requires you to import a model converted to the TF.JS format over file system or http/https endpoint but you cannot simply access a docker image exporting a scoring API endpoint.  You need to export your model, convert it to TF.JS and import it to Vott over url or file system path.

**Comment by JacopoMangiavacchi** [comment]
Submitted PR #880 to fix regex validation string to support more complex urls
