### ISSUE TITLE
[Feature] Make Security Tokens Optional

### ISSUE THREAD

**Issue by MichaelCVelez** [microsoft/VoTT#835]
**Is your feature request related to a problem? Please describe.**
If a project does not contain sensitive information, it is forced to be encrypted anyway and requires a matching token to be opened. This becomes an obstacle when trying to share projects.

**Describe the solution you'd like**
I would like to be able to turn token generation off before creating a project to make it accessible to others regardless of which tokens they have. Ideally you can also switch it back on before creating another project at any time.

**Describe alternatives you've considered**
I need to view several users projects and each have generated a unique token. I could request these tokens from them but they work on rotating schedules and could take a full week to get those tokens from them. I could have them create one token that is shared between all projects, but they could forget to use that token on project creation. 

**Additional context**
Since this is an internal group, we should be able to open each other’s projects without issue or added complexity if there isn’t sensitive information.

**Comment by ajansenn** [comment]
+second that
