### ISSUE TITLE
the JPG is a Fake JPG

### ISSUE THREAD

**Issue by eudora-jia** [microsoft/VoTT#838]
**the JPG is a Fake JPG**
When I downloaded a VOTT from the release address, I used the tool to label my video for my train task with caffe. for some reasons, I need to check the IMG, So I opened a img in notepad++  which is saved by the VOTT  using my video, OMG, I found the PNG header in there.

**Check Again**
Steps to reproduce theu:
1. I still trained my CNN net until I file the img 
it is STILL BGRA

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by mloenow** [comment]
@eudora-jia I've submitted https://github.com/microsoft/VoTT/pull/801 with a fix some time ago, but it seems the project has gone stale. Perhaps you can patch it locally?

**Comment by eudora-jia** [comment]
it is just a exe file, what you said  means git clone one,an build myself

**Comment by mloenow** [comment]
@eudora-jia Yes 👍

**Comment by eudora-jia** [comment]
> @eudora-jia Yes 👍

thks

**Comment by JacopoMangiavacchi** [comment]
PR has been merged into develop branch.  Thanks again.
