### ISSUE TITLE
Thumbnails aren't shown in the sidebar

### ISSUE THREAD

**Issue by pantuwong** [microsoft/VoTT#962]
**Describe the bug**
I have clone this repo and try to use it. It works well except the thumbnails in the left sidebar. I cannot see any images there. However, when I click up/down button on the toolbar, I can change image successfully.

I try to debug and stuck at the `editorSideBar.tsx`. I don't know why the List element not call `this.rowRenderer` function. I try to do console.log at the rowRenderer function but nothing print out.

**Screenshots**
![Screenshot from 2020-05-11 14-41-38](https://user-images.githubusercontent.com/4495823/81554271-ae899200-93b0-11ea-84d7-91af4ca12f97.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser Chrome

**Comment by StevenOoi1996** [comment]
I had the same problem, but the previous VoTT i used, did not show this problem
