### ISSUE TITLE
Can VoTT export the labels in COCO format？

### ISSUE THREAD

**Issue by songyuc** [microsoft/VoTT#970]
Hi guys,
I am a learner of CV (Computer Vision).
And I want to know whether VoTT can export the labels in COCO format?

Your answer or idea will be appreciated!

**Comment by jeongjinhwi** [comment]
No, It can't....
So, I exported with pascal voc and used open source code.
I used this code : https://github.com/yukkyo/voc2coco/blob/master/voc2coco.py

**Comment by songyuc** [comment]
Hi @jeongjinhwi , 
thanks sincerely for the sharing!
