### ISSUE TITLE
Does VoTT just support no more than 10 tags?

### ISSUE THREAD

**Issue by songyuc** [microsoft/VoTT#972]
Hi guys,
I am learning about using VoTT, and I don't know how to switch another tag beyond the first 10 tags, as the first 10 tags can be applied using the hot keys.
And I have more than 80 tags in my task.

Any answer or idea will be appreciated!

**Comment by fishcharlie** [comment]
You should be able to just click on the tag after drawing your region.

**Comment by songyuc** [comment]
@fishcharlie , thanks sincerely for your guide!
