### ISSUE TITLE
When does VOTT v2 support yolo format?

### ISSUE THREAD

**Issue by x12901** [microsoft/VoTT#994]
I really like this project, but it doesn't support exporting to yolo format. This makes me sad.There are a lot of people using yolo and I hope it helps those people!

**Comment by yeldarby** [comment]
@x12901 - we created a tool that can [convert VoTT JSON to any other format](https://roboflow.com/formats/vott-json) (including [VoTT to YOLO](https://roboflow.com/convert/vott-json-to-yolo-darknet-txt)). Hope it helps!

**Comment by x12901** [comment]
Thank you

**Comment by bdockbockd** [comment]
Do we have converter from YOLO to VoTT? I want to relabel my existing dataset.
